version: '3.3'  

services:  
  neo4j:  
    image: neo4j:5.19  
    ports:  
      - 7687:7687  
      - 7474:7474  
    volumes:  
      - $PWD/neo4j/data:/data  
    environment:  
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}  
      - NEO4J_PLUGINS=["apoc"]  
      - NEO4J_db_tx__log_rotation_retention__policy=false  
    healthcheck:  
      test:  
        [  
          "CMD-SHELL",  
          "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1",  
        ]  
      interval: 5s  
      timeout: 3s  
      retries: 5  
    networks:  
      - net  

  api:  
    build:  
      context: ./api  
    environment:  
      - NEO4J_URI=${NEO4J_URI}  
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}  
      - NEO4J_USERNAME=${NEO4J_USERNAME}  
      - OPENAI_API_KEY=${OPENAI_API_KEY}  
    networks:  
      - net  
    depends_on:  
      - neo4j  
    volumes:
      - ./api:/app
    ports:  
      - 8000:8000  

  ui:  
    build:  
      context: ./ui  
    environment:  
      - VITE_API_BASE_URL=${BASE_API_URL}  
    networks:  
      - net  
    depends_on:  
      - neo4j  
    volumes:  
      - ./ui:/app  
      - /app/node_modules  
    ports:  
      - 3000:3000  

networks:  
  net:  
    driver: bridge
